#!/bin/bash

# Create the .pixelfiles Directory
mkdir -p "$HOME"/.pixelfiles
PFDIR="$HOME"/.pixelfiles

if [ "$1" == "all" ] ; then 
    # Install All Packages
    sudo pacman -Syu
    sudo pacman -S shotgun hacksaw wget noto-font ttf-ubuntumono-nerd noto-font-cjk noto-font-emoji ttf-ubuntu-font-family unzip awesome polkit-gnome sddm rofi kitty thunar brightnessctl picom volumeicon cbatticon network-manager-applet slock starship exa bat zsh vim firefox android-file-transfer
    
    # Enable sddm
    sudo systemctl enable sddm
    
    # Cloning Pixelfiles 
    git clone --recurse-submodules --remote-submodules https://github.com/Mohannadk28/pixelfiles-apps "$PFDIR"/pixelfiles-apps
    git clone --recurse-submodules --remote-submodules https://github.com/Mohannadk28/pixelfiles-term "$PFDIR"/pixelfiles-term
    git clone --recurse-submodules --remote-submodules https://github.com/Mohannadk28/pixelfiles-desktop "$PFDIR"/pixelfiles-desktop
    
    # Allow the Setup Scripts to Execute
    chmod +x "$PFDIR"/pixelfiles-apps/setup-apps.sh
    chmod +x "$PFDIR"/pixelfiles-term/setup-term.sh
    chmod +x "$PFDIR"/pixelfiles-desktop/setup-desktop.sh    

    # Setting up the Pixelfiles
    bash "$PFDIR"/pixelfiles-apps/setup-apps.sh
    bash "$PFDIR"/pixelfiles-term/setup-term.sh
    bash "$PFDIR"/pixelfiles-desktop/setup-desktop.sh

    # Installing the Icon Pack
    wget -qO- https://git.io/papirus-icon-theme-install | sh

    # Install the Nordic-GTK Theme
    mkdir -p "$HOME"/.themes
    cd "$HOME"/.themes || return
    wget https://github.com/EliverLara/Nordic/releases/download/v2.2.0/Nordic-bluish-accent-standard-buttons-v40.tar.xz
    tar -xf  Nordic-bluish-accent-standard-buttons-v40.tar.xz
    rm -rf  Nordic-bluish-accent-standard-buttons-v40.tar.xz
elif [ "$1" == "term" ] ; then
    # Install Shell Packages
    sudo pacman -Syu
    sudo pacman -S zsh starship exa bat ttf-ubuntumono-nerd
    
    # Clone the Pixelfiles
    git clone --recurse-submodules --remote-submodules https://github.com/Mohannadk28/pixelfiles-term "$PFDIR"/pixelfiles-term

    # Allow the Setup Script to Execute
    chmod +x "$PFDIR"/pixelfiles-term/setup-term.sh

    # Setting up the Pixelfiles
    bash "$PFDIR"/pixelfiles-term/setup-term.sh
fi
